version: '3'
services:
  parser:
    build:
      context: ./parser_service
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - shared_data:/app/invoices

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - shared_data:/app/invoices

volumes:
  shared_data: