version: '3'
services:
  parser:
    build:
      context: ./parser_service
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - shared_data:/app/invoices
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - shared_data:/app/invoices

  nestapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - shared_data:/app/invoices
    depends_on:
      - redis

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres_pw'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  shared_data:
  database: