version: '3'
services:
  parser:
    build:
      context: ./parser_service
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - shared_data:/app/invoices
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - shared_data:/app/invoices

  nestapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - shared_data:/app/invoices
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy


  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres_pw'
      POSTGRES_DB: 'mydb'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  shared_data:
  database: